改变延迟规则，将服务器与本地版本分成两个文件
TechCiel/jlu-health-reporter pull request #9
Opened 2020-11-20 04:27 UTC by Lonble

对原程序做出以下改变：
1.分成两个python脚本，分别用于服务器和本地。服务器版本有随机延迟、更长的重试间隔；本地版本没有随机延迟、重试间隔很短，适合手动运行，短时间内完成打卡任务。
2.将随机延迟加入每一个线程内，更适合多任务情况。
3.每次重试会检查当前时间，如果不在打卡时间内则退出当前线程
4.精简记录信息

2020-11-20 18:00 UTC, TechCiel requested changes
我猜测作者是为了差异化运行场景选择了开两个文件，但是这是极不划算的，一则需要同时维护两个文件，二则会破坏向前兼容性。如果确实需要这样的功能，应该考虑配置文件或者环境变量传入，但是我也不打算做出如是的更改。

目前 500 次重试、10 秒超时、2 秒线程间隔、10 分钟随机延迟的参数，我是经过反复考虑的，因素主要有几方面：
- 如果有任务配置有误，不能容许无限运行，因此要限制 retry ，但若 retry 太少次数还会导致土豆爆炸时无法正常打卡
- retry*timeout 太大会干涉到下一次打卡（目前干涉极限是 11 小时）
- timeout 和 interval 太低会给服务器带来压力，太高会导致效率太低，无法短时间解决战斗
- timeout 太低会让越洋打卡同学的网络面临一些挑战

目前的配置大致能保证服务器正常时在几分钟内解决战斗，且不给服务器产生瞬时并发高峰，即使服务器挂一挂，不太太太久也能正常重试打卡，且线程间有一定错落。

对于你当前的 pr ，我逐条答复：

1. 首先上面已经说明了，分两个文件是弊大于利的，且当前的默认参数对各种情况适用性均可接受，按 Control-C 可以跳过延时，能满足服务器和本地的使用。
2. 随机延迟的的引入，是防止大家都使用默认的定时配置，造成服务器负载尖峰，单个实例的线程间本身有错落，引入这一更改实际意义并不大。
3. 现在满打满算跑满 retry 也不会干到下一个时段去，而且也可以通过 Wiki 里的 conditions 黑魔法完成类似功能。
4. 因为你把原文件删了没得 diff 看不出来改了啥。

综上，这个 PR 暂时不予合并，还请理解。

2020-11-20 18:03 UTC, TechCiel requested changes
首先还是很感谢您的关注和贡献，但是由于先期缺少沟通，有一些问题我与您的想法尚有很大分歧，所以暂时不能合并，还请详细阐述下您的考量。

另外，欢迎参照 README.md 中的联系方式进群讨论打卡的未来。

2020-11-21 11:38 UTC, Lonble commented
首先感谢你的认真答复。
我的分支只是根据我个人的使用需求（给全班打卡）做出了一些更改，并没有考虑到整个项目的发展。改动幅度有些大，贸然提交合并请求确实不太稳妥。提交请求的时候我就想到了大概率不会被合并，所以我将关闭这次合并请求，并说一下对其中某个改变的看法。

---

我说一下对日志信息的想法。
因为我要同时给许多人打卡，如果有尝试失败的情况，再加上多线程并行，会导致日志信息顺序混乱，很难分析。
在我个人的改动里，我保留了原来的日志信息（定向到标准错误），也加了内容到标准输出，仅仅是把每个成功打卡人的信息打印，每人一行，这样就能通过检查日志发现有哪些人打卡成功了。然后通过服务器的检测脚本向我通知打卡情况。

---

最后感谢你的成果帮助了许多人。

2020-11-21 11:38 UTC, closed without merging

2020-11-22 01:25 UTC, TechCiel commented
> 我说一下对日志信息的想法。
> 因为我要同时给许多人打卡，如果有尝试失败的情况，再加上多线程并行，会导致日志信息顺序混乱，很难分析。
> 在我个人的改动里，我保留了原来的日志信息（定向到标准错误），也加了内容到标准输出，仅仅是把每个成功打卡人的信息打印，每人一行，这样就能通过检查日志发现有哪些人打卡成功了。然后通过服务器的检测脚本向我通知打卡情况。

```
grep Success /path/to/reporter.log
grep Failed /path/to/reporter.log
```